version: 1.0.{build}
before_build:
- cmd: nuget restore FichaTecnica\FichaTecnica.sln
build:
  verbosity: minimal
notifications:
- provider: Slack
  auth_token:
    secure: 0kHKEtcLUkP669vRMKeIffDHGAprouH4Jmry1ulH0rSPDIEhLWxOZmhzzZYtv2WLUA9jNzTajzU3X9rKjYOLxg==
  channel: kali
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
