version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore FichaTecnica\FichaTecnica.sln
build:
  verbosity: minimal
notifications:
  - provider: Slack
    auth_token:
        secure: 0kHKEtcLUkP669vRMKeIffDHGAprouH4Jmry1ulH0rSPDIEhLWxOZmhzzZYtv2WLUA9jNzTajzU3X9rKjYOLxg==
    channel: kali
